{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.2.aar",
          "url": "idnow-android-eid-sdk-2.7.2.aar",
          "size": 5716303,
          "sha512": "42724dbf19704f4d51ce256cb7fbb791c7186a89260bd5cebf02e566cbe95f5b1b273900c692fa2a3ca047bc86d19b659a0ac75e935da4fb5e66447c7127d9e4",
          "sha256": "ddcb94a670558df29a64849d271a1f0e9ce19bcf09e5e321470b2823bda9e5f2",
          "sha1": "1c186a621684ba83ecfbe9b1c288208c3c1d2d02",
          "md5": "893ca7da5e5c5e6ae49afcc873426947"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.2.aar",
          "url": "idnow-android-eid-sdk-2.7.2.aar",
          "size": 5716303,
          "sha512": "42724dbf19704f4d51ce256cb7fbb791c7186a89260bd5cebf02e566cbe95f5b1b273900c692fa2a3ca047bc86d19b659a0ac75e935da4fb5e66447c7127d9e4",
          "sha256": "ddcb94a670558df29a64849d271a1f0e9ce19bcf09e5e321470b2823bda9e5f2",
          "sha1": "1c186a621684ba83ecfbe9b1c288208c3c1d2d02",
          "md5": "893ca7da5e5c5e6ae49afcc873426947"
        }
      ]
    }
  ]
}
