{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.0.3.aar",
          "url": "idnow-android-eid-sdk-3.0.3.aar",
          "size": 5672562,
          "sha512": "f646dc9b93af47f4a8beee685eaeb508f8899b9e8757002432fb14717e729d5682e5daff2d9ab90dd40368d9f1308ae858b5ae2c9d56d9986c5796992bad06cb",
          "sha256": "f10a13bcab56bb454f63741ab397bc8bdbd0b0b3065e760d3d152db20cedd166",
          "sha1": "3b296fcf4e7a8e0fa4a2c05a56b2e281884938ff",
          "md5": "62e839303b3a34635fc7712247301944"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.0.3.aar",
          "url": "idnow-android-eid-sdk-3.0.3.aar",
          "size": 5672562,
          "sha512": "f646dc9b93af47f4a8beee685eaeb508f8899b9e8757002432fb14717e729d5682e5daff2d9ab90dd40368d9f1308ae858b5ae2c9d56d9986c5796992bad06cb",
          "sha256": "f10a13bcab56bb454f63741ab397bc8bdbd0b0b3065e760d3d152db20cedd166",
          "sha1": "3b296fcf4e7a8e0fa4a2c05a56b2e281884938ff",
          "md5": "62e839303b3a34635fc7712247301944"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.0.3-sources.jar",
          "url": "idnow-android-eid-sdk-3.0.3-sources.jar",
          "size": 241919,
          "sha512": "35c00366665e24892b037141f7864c2d395c316415af1d1ce4885a4573593449e72f5983b3968cf58419d31fee57e260a5e7b8de22d8d64aad3e61071e672fc9",
          "sha256": "8d2be82e0ec877ba52579258f12d6dea389b8dbf0eef182c8edee9a261dd71be",
          "sha1": "05132399765f3f5164c3195f0d3c902a95d02424",
          "md5": "b87ff91671ba9718525e9b5876cf78de"
        }
      ]
    }
  ]
}
