{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7rt3ujezzrcgxopyi7uz6zntv4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.0.aar",
          "url": "idnow-android-eid-sdk-2.7.0.aar",
          "size": 5693264,
          "sha512": "8f4b3c9142da3449d44be6713ce1cad8a15fa94b2da725358f66215251ce8b11d3f189fb495e905f2ff19689a230f03cda29b18ec714c7059a3c34dcbbdf1150",
          "sha256": "13cb5977486f9281dbb63dd44dd2344f465a162623ee77c405e0d7c29c9fd855",
          "sha1": "4a22c25395331c0fcfffc31e1f77267365ca5fec",
          "md5": "0cbeabd5dd4d1e7b7fb87846e12d8b70"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.0.aar",
          "url": "idnow-android-eid-sdk-2.7.0.aar",
          "size": 5693264,
          "sha512": "8f4b3c9142da3449d44be6713ce1cad8a15fa94b2da725358f66215251ce8b11d3f189fb495e905f2ff19689a230f03cda29b18ec714c7059a3c34dcbbdf1150",
          "sha256": "13cb5977486f9281dbb63dd44dd2344f465a162623ee77c405e0d7c29c9fd855",
          "sha1": "4a22c25395331c0fcfffc31e1f77267365ca5fec",
          "md5": "0cbeabd5dd4d1e7b7fb87846e12d8b70"
        }
      ]
    }
  ]
}
