{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hg72n5xmxrak7jsb3vmp7skxg4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.0.aar",
          "url": "idnow-android-eid-sdk-2.5.0.aar",
          "size": 5698999,
          "sha512": "99e69573ba02d9edef750ad5dc66641513a92ad311009ea3ea2390413150859c0f553c8b94961e23fe8016a5c2cee2332e762e3c7ff4ee486cc5bfdd0f775760",
          "sha256": "158a26d2893b347b3f8014d80d0dbdf6dbf0cb94b244f8fdbc95f07b678da972",
          "sha1": "d4a42380993b49c670c445178e15746310922e2a",
          "md5": "096a698bb0349b00047cb34d4c96d168"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.0.aar",
          "url": "idnow-android-eid-sdk-2.5.0.aar",
          "size": 5698999,
          "sha512": "99e69573ba02d9edef750ad5dc66641513a92ad311009ea3ea2390413150859c0f553c8b94961e23fe8016a5c2cee2332e762e3c7ff4ee486cc5bfdd0f775760",
          "sha256": "158a26d2893b347b3f8014d80d0dbdf6dbf0cb94b244f8fdbc95f07b678da972",
          "sha1": "d4a42380993b49c670c445178e15746310922e2a",
          "md5": "096a698bb0349b00047cb34d4c96d168"
        }
      ]
    }
  ]
}
