{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "puns4w5gpveh5hzyrbdnomqzda"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-1.6.0.aar",
          "url": "idnow-android-eid-sdk-1.6.0.aar",
          "size": 5266327,
          "sha512": "30794f7ddfff07a408f28c67340cb69a4d1a4b9524502e68bc1ddbe5aef825917ca68910c6506d8b2ec5706723516837f0d9d2fa8f2fa6c06311a7f729181ce9",
          "sha256": "70865f92183cac94917a7a214ef67f6b4b4f184a5ed5445698bf5859a96c1bba",
          "sha1": "48bd0e5796d4759f081d7297db89b322327304c6",
          "md5": "0464f22da90cd029f17ba76c05fc2ee7"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-1.6.0.aar",
          "url": "idnow-android-eid-sdk-1.6.0.aar",
          "size": 5266327,
          "sha512": "30794f7ddfff07a408f28c67340cb69a4d1a4b9524502e68bc1ddbe5aef825917ca68910c6506d8b2ec5706723516837f0d9d2fa8f2fa6c06311a7f729181ce9",
          "sha256": "70865f92183cac94917a7a214ef67f6b4b4f184a5ed5445698bf5859a96c1bba",
          "sha1": "48bd0e5796d4759f081d7297db89b322327304c6",
          "md5": "0464f22da90cd029f17ba76c05fc2ee7"
        }
      ]
    }
  ]
}
