{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.sdk",
    "module": "idnow-android-sdk",
    "version": "5.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gkzg7ii34vajvmgylvqq2n7qse"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-5.0.2.aar",
          "url": "idnow-android-sdk-5.0.2.aar",
          "size": 35862623,
          "sha512": "eebc8696015f8b58a0ee433637b407e0e8ec9890bcc59757b3c3e1284fb0d46c60aeeb65f5f70caca7a2bc728d86bd0444d09b362d9ec5d74608c484bc12119f",
          "sha256": "045be4aab10f99c4415dc14d6b6053e4fb93e603cc13137bf361fa9a8829ad60",
          "sha1": "1b9789c1a3ccc2caed0542bfc3b73dd51dd5c8bd",
          "md5": "7598744c87dbac777e528860e6501159"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-5.0.2.aar",
          "url": "idnow-android-sdk-5.0.2.aar",
          "size": 35862623,
          "sha512": "eebc8696015f8b58a0ee433637b407e0e8ec9890bcc59757b3c3e1284fb0d46c60aeeb65f5f70caca7a2bc728d86bd0444d09b362d9ec5d74608c484bc12119f",
          "sha256": "045be4aab10f99c4415dc14d6b6053e4fb93e603cc13137bf361fa9a8829ad60",
          "sha1": "1b9789c1a3ccc2caed0542bfc3b73dd51dd5c8bd",
          "md5": "7598744c87dbac777e528860e6501159"
        }
      ]
    }
  ]
}
