{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gzmwtysb2zf55mw6u536r2523i"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.0.2.aar",
          "url": "idnow-android-eid-sdk-2.0.2.aar",
          "size": 8750007,
          "sha512": "b8f03eecda4150b306fb45d2673db320d789c3fd7aaef0d920a1ab11eb61b37fabbcb8799c8671ec2f406cdce903a9d62c62adc54b9f7e7778beea72354af7ef",
          "sha256": "d9c340e5b68396023e88ee929b0e71d5361f99d270848b8416910b358f59c688",
          "sha1": "e50eaa71a329fe66639c4157cd089a9f03e84cb2",
          "md5": "171d294833c3817c542f6b41e9fe0ef2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.0.2.aar",
          "url": "idnow-android-eid-sdk-2.0.2.aar",
          "size": 8750007,
          "sha512": "b8f03eecda4150b306fb45d2673db320d789c3fd7aaef0d920a1ab11eb61b37fabbcb8799c8671ec2f406cdce903a9d62c62adc54b9f7e7778beea72354af7ef",
          "sha256": "d9c340e5b68396023e88ee929b0e71d5361f99d270848b8416910b358f59c688",
          "sha1": "e50eaa71a329fe66639c4157cd089a9f03e84cb2",
          "md5": "171d294833c3817c542f6b41e9fe0ef2"
        }
      ]
    }
  ]
}
