{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.0.2.aar",
          "url": "idnow-android-eid-sdk-3.0.2.aar",
          "size": 5666117,
          "sha512": "aad6712254c3ff8aedaa3f97989cddf0b05178c8c1fb9d7f56ec51296815db18ac07f3a0d8a142b1f41623eaa05b33b5f2e2a944ebacd01a1444153960992ba2",
          "sha256": "f4e33426cd4a2b8638189d39d76f0243b890496eebdc7335876b5f916f14e4f0",
          "sha1": "5f7529138ce7e1139607b23af7a70a2a0aae175e",
          "md5": "0aa95e555da332e5cc731a38ee54fc4f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.0.2.aar",
          "url": "idnow-android-eid-sdk-3.0.2.aar",
          "size": 5666117,
          "sha512": "aad6712254c3ff8aedaa3f97989cddf0b05178c8c1fb9d7f56ec51296815db18ac07f3a0d8a142b1f41623eaa05b33b5f2e2a944ebacd01a1444153960992ba2",
          "sha256": "f4e33426cd4a2b8638189d39d76f0243b890496eebdc7335876b5f916f14e4f0",
          "sha1": "5f7529138ce7e1139607b23af7a70a2a0aae175e",
          "md5": "0aa95e555da332e5cc731a38ee54fc4f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.0.2-sources.jar",
          "url": "idnow-android-eid-sdk-3.0.2-sources.jar",
          "size": 238593,
          "sha512": "051c8d14445419bc210b129a70529649d8ba57de16fa05ebfb8384d635bedcdbd693c64f4d6e95a1198d5312df9b76bf285de94933576402faf8d28090585ed6",
          "sha256": "6bff0f28fe02b2dcc4b5ecdfef9266098afcaf9b117ff5de34e596ba2dcc7075",
          "sha1": "044e3d796e74d4928a5d17581d301fddc5f011e0",
          "md5": "86338226c0c19dd81280106af611492b"
        }
      ]
    }
  ]
}
