{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.2.0.aar",
          "url": "idnow-android-eid-sdk-3.2.0.aar",
          "size": 5609741,
          "sha512": "0f218ec4221eb4f8837a674a7ce3e761ff15f1f71ed48d2b174be5969dd9a362435762879b77ff48e5385b755d154bf5367449f619535d12e969ea577119aabe",
          "sha256": "944b87188547d7cffd01e6391b0efec50e9feac35d7d28d83f4cae2b75eef046",
          "sha1": "44d2acc73210cbe07fa2be5af499a881a4c51d70",
          "md5": "e32af0e842cf8f6641ccc17d72aa3013"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.2.0.aar",
          "url": "idnow-android-eid-sdk-3.2.0.aar",
          "size": 5609741,
          "sha512": "0f218ec4221eb4f8837a674a7ce3e761ff15f1f71ed48d2b174be5969dd9a362435762879b77ff48e5385b755d154bf5367449f619535d12e969ea577119aabe",
          "sha256": "944b87188547d7cffd01e6391b0efec50e9feac35d7d28d83f4cae2b75eef046",
          "sha1": "44d2acc73210cbe07fa2be5af499a881a4c51d70",
          "md5": "e32af0e842cf8f6641ccc17d72aa3013"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.2.0-sources.jar",
          "url": "idnow-android-eid-sdk-3.2.0-sources.jar",
          "size": 248637,
          "sha512": "fe0b0dea8429d970c2e08af72b64d7e415f0bab46c9ecf0d9d03c0f309c3d7adf02f33ad77531a1a5b90b6e543c91c332a52112733d656013cefa6ac1faeed4b",
          "sha256": "e79e739ab4c6c23ab83e594fcfd4b7332d1560138fa31caafb5c470d0c6de410",
          "sha1": "9c01de14b818c07a790d1f3c3720255b2d2a92eb",
          "md5": "ed0f191ac7a4703efcae123a3ff1c9ac"
        }
      ]
    }
  ]
}
