{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "75g6adz2qvdjbbl2tigppi4psq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.5.aar",
          "url": "idnow-android-eid-sdk-2.5.5.aar",
          "size": 5692916,
          "sha512": "182843357c2162e23c46835c4ddb2c0ae5eb3df3cdf58969ea6fd317959ccb7e0a4e57861f4f177de74abc3989664cebbf86e8692419b8b999fe8c1ac81f5513",
          "sha256": "3e524aaa757feff08e49db61214401d0b06205c3dd60760ff925b027e53f0f6a",
          "sha1": "56f2202986d7044bfd0802ea116eaeb188befe97",
          "md5": "fbe8fc86071164290aaa230508e383f6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.5.aar",
          "url": "idnow-android-eid-sdk-2.5.5.aar",
          "size": 5692916,
          "sha512": "182843357c2162e23c46835c4ddb2c0ae5eb3df3cdf58969ea6fd317959ccb7e0a4e57861f4f177de74abc3989664cebbf86e8692419b8b999fe8c1ac81f5513",
          "sha256": "3e524aaa757feff08e49db61214401d0b06205c3dd60760ff925b027e53f0f6a",
          "sha1": "56f2202986d7044bfd0802ea116eaeb188befe97",
          "md5": "fbe8fc86071164290aaa230508e383f6"
        }
      ]
    }
  ]
}
