{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.4.aar",
          "url": "idnow-android-eid-sdk-3.4.4.aar",
          "size": 5723145,
          "sha512": "c32fd1f61550fa74c74317640a6c00f49a699f70457a80846c458868baab724a97575ed93b8bf959a5a529998bf0af23cbaa744f708b0f5ae609fb2d54c9fe14",
          "sha256": "a9c19754b2be73f38ee59b918f8c8f6af0a02c90f8912165304ec77a7a734a9a",
          "sha1": "4c8cfa298eeab0162eba48127373d6eb5f0ee423",
          "md5": "fd3c3da762e1b762f6a0d205d3e60580"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.24.4"
          }
        },
        {
          "group": "com.governikus",
          "module": "ausweisapp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.4.aar",
          "url": "idnow-android-eid-sdk-3.4.4.aar",
          "size": 5723145,
          "sha512": "c32fd1f61550fa74c74317640a6c00f49a699f70457a80846c458868baab724a97575ed93b8bf959a5a529998bf0af23cbaa744f708b0f5ae609fb2d54c9fe14",
          "sha256": "a9c19754b2be73f38ee59b918f8c8f6af0a02c90f8912165304ec77a7a734a9a",
          "sha1": "4c8cfa298eeab0162eba48127373d6eb5f0ee423",
          "md5": "fd3c3da762e1b762f6a0d205d3e60580"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.4-sources.jar",
          "url": "idnow-android-eid-sdk-3.4.4-sources.jar",
          "size": 287625,
          "sha512": "c6c4a47e978c0e1f62a67c755683d380dce73bfcb0ad4d3af91f75a8b758869e46ea874d86ceba33fdca85cfa4e68a61dbf73720480457b00f3390a3969690d4",
          "sha256": "35f0554280fd94ced2d53446799295ef8407d88b2ed063b8dc58b7b36cabdbe9",
          "sha1": "3b0c16f7076356c12ead2c0ea1110c67f4f439d2",
          "md5": "fbbdf8612329bd99a8c7af4d6c93ee23"
        }
      ]
    }
  ]
}
