{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "wi3nuxglpfbwvbjj5a47e5pgba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.2.0.aar",
          "url": "idnow-android-eid-sdk-2.2.0.aar",
          "size": 5688584,
          "sha512": "fed5b8eb8f9390b401cff53cec6261773140a13ec2b48c7dbcdaabf7fa9a9a824c7eb8be9777ec63cf46ac60889979b86f65b37c43efc02d5dfbf3c4d2fe1aab",
          "sha256": "ea19fc75cda252a387c8c59cce17824fc1c8d6a6b6941c2cd6927232aabb60a6",
          "sha1": "9149b3155593619b1e438a174faaf5494a337bd1",
          "md5": "27fac2ebadecb5f5443a1f728931afc5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.2.0.aar",
          "url": "idnow-android-eid-sdk-2.2.0.aar",
          "size": 5688584,
          "sha512": "fed5b8eb8f9390b401cff53cec6261773140a13ec2b48c7dbcdaabf7fa9a9a824c7eb8be9777ec63cf46ac60889979b86f65b37c43efc02d5dfbf3c4d2fe1aab",
          "sha256": "ea19fc75cda252a387c8c59cce17824fc1c8d6a6b6941c2cd6927232aabb60a6",
          "sha1": "9149b3155593619b1e438a174faaf5494a337bd1",
          "md5": "27fac2ebadecb5f5443a1f728931afc5"
        }
      ]
    }
  ]
}
