{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.3.aar",
          "url": "idnow-android-eid-sdk-3.4.3.aar",
          "size": 5720751,
          "sha512": "53ae88648316b124105b9adbf6c79b957842a7b24cae9fe4cb4f612a83b253bae9293e610bb4248a74aaa44cf96f06d9e306dd61c3c7e74bf38270627c80cfbf",
          "sha256": "6fee166eeb0e3fbb71881f7fe90ffcbe6fc19b730329c00287a59efad81bf9b9",
          "sha1": "dc9fffac4ebc248aad9cbefc814a959cefe7e4ee",
          "md5": "05e7c8eb08fc93bba6533d58d5b0b86e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.24.4"
          }
        },
        {
          "group": "com.governikus",
          "module": "ausweisapp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.3.aar",
          "url": "idnow-android-eid-sdk-3.4.3.aar",
          "size": 5720751,
          "sha512": "53ae88648316b124105b9adbf6c79b957842a7b24cae9fe4cb4f612a83b253bae9293e610bb4248a74aaa44cf96f06d9e306dd61c3c7e74bf38270627c80cfbf",
          "sha256": "6fee166eeb0e3fbb71881f7fe90ffcbe6fc19b730329c00287a59efad81bf9b9",
          "sha1": "dc9fffac4ebc248aad9cbefc814a959cefe7e4ee",
          "md5": "05e7c8eb08fc93bba6533d58d5b0b86e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.3-sources.jar",
          "url": "idnow-android-eid-sdk-3.4.3-sources.jar",
          "size": 285945,
          "sha512": "8073efeaec68ec451151439e76fd2a6b2499d7fd9bf44282a95e1591a15eb1440de29d206deadd1ede39a003a5d49451eec95db96c906f769e22465b308c9a36",
          "sha256": "ebfbc73188158744e7a2198bca6355899ca6a31b04692f933e7d05467fe18c06",
          "sha1": "32edccd233067ae97b8842baa56da1c849a361d3",
          "md5": "5f91a68a0789e40ee51bf3109bc29df8"
        }
      ]
    }
  ]
}
