{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.1.aar",
          "url": "idnow-android-eid-sdk-3.4.1.aar",
          "size": 5726142,
          "sha512": "fbf24ff4b232c68d3d8afdce508c913e11e00e511a2e5f69960fd793b969ef6531494ea9b964d062f71ba31c1ef12d0eaaea8a99a784a4a74272d079e372cd64",
          "sha256": "8b00e453e35e4b1f6b0a1b7bf690e3bb4a93c767106d3c0b38d61a15cd192dea",
          "sha1": "f73cdd1971c79b3f35574317a74a1b09fa991ead",
          "md5": "26820a65dec5528ef1a23dd9e2243dee"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.24.4"
          }
        },
        {
          "group": "com.governikus",
          "module": "ausweisapp",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.1.aar",
          "url": "idnow-android-eid-sdk-3.4.1.aar",
          "size": 5726142,
          "sha512": "fbf24ff4b232c68d3d8afdce508c913e11e00e511a2e5f69960fd793b969ef6531494ea9b964d062f71ba31c1ef12d0eaaea8a99a784a4a74272d079e372cd64",
          "sha256": "8b00e453e35e4b1f6b0a1b7bf690e3bb4a93c767106d3c0b38d61a15cd192dea",
          "sha1": "f73cdd1971c79b3f35574317a74a1b09fa991ead",
          "md5": "26820a65dec5528ef1a23dd9e2243dee"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.1-sources.jar",
          "url": "idnow-android-eid-sdk-3.4.1-sources.jar",
          "size": 292873,
          "sha512": "30af6daa54f795996e7a6a12fcb19d8c3a11f8b17da219521fb816e501fc47e38cebfad22335f8af35b6fefa43d471a15a20b695be9e7661f8d9fe5710539700",
          "sha256": "25ea86540f0885446d9a6fd2ef02633f35f43eac4e70355a332a99457db84436",
          "sha1": "401f797eeb4f842320217085beea2948ce49c5ca",
          "md5": "66ff263664d152ac5064bb1a7c3a3a89"
        }
      ]
    }
  ]
}
