{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.1.aar",
          "url": "idnow-android-eid-sdk-3.4.1.aar",
          "size": 5722539,
          "sha512": "46d21dac516ba9739692b2146eb3b9e4abd8c7343c5a97923a5b86050daa5177971d7f2e7db3bfcb4198b8bbfa86fd4445dd1675156cbbfac0e40692115cae7b",
          "sha256": "6aef21321befd2288c0a90f9b2a4389e6c875a3a927b4c13c20454153dab71bf",
          "sha1": "191fff005808f89bd6e302033273e7b0b947bb74",
          "md5": "8e870e1aa921d5adf3b319ebc7a067a3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.24.4"
          }
        },
        {
          "group": "com.governikus",
          "module": "ausweisapp",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.1.aar",
          "url": "idnow-android-eid-sdk-3.4.1.aar",
          "size": 5722539,
          "sha512": "46d21dac516ba9739692b2146eb3b9e4abd8c7343c5a97923a5b86050daa5177971d7f2e7db3bfcb4198b8bbfa86fd4445dd1675156cbbfac0e40692115cae7b",
          "sha256": "6aef21321befd2288c0a90f9b2a4389e6c875a3a927b4c13c20454153dab71bf",
          "sha1": "191fff005808f89bd6e302033273e7b0b947bb74",
          "md5": "8e870e1aa921d5adf3b319ebc7a067a3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.4.1-sources.jar",
          "url": "idnow-android-eid-sdk-3.4.1-sources.jar",
          "size": 291433,
          "sha512": "b475e0cfdc26c5a82f8e810fc5c040e63dba0dd362dfa80e2f8bf7d83926f577f042ce8c9b7f5ece093034d927c4413891742ab8474fd5d5454469ce7b998ce0",
          "sha256": "d8f540504ef6321eca0d7e0a059cac207fef1df20f66b269652c5224db06d197",
          "sha1": "9e5ca6c0d6bef951166d0d61bb911d3ca89bd516",
          "md5": "df14b356e8025ec8ddf6c7d983816f35"
        }
      ]
    }
  ]
}
