{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ybq5sl3npja5jkmu3yg7njq7dq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.4.0.aar",
          "url": "idnow-android-eid-sdk-2.4.0.aar",
          "size": 5698631,
          "sha512": "623bb25333edae5745a56c13de0d93996a294c620fb25d405f1e00048771bd41ff50fb33f75a60463c6f02786b91f0c577e55deca9be144fde8cf7c4c13afa6a",
          "sha256": "973752cee3a17030e2ef7060998776766c1fdeeacd7e93749bf35bd2e9fe4d53",
          "sha1": "dd042c3b1e488997aca282730faf1138a330e7dc",
          "md5": "8afb1b036b906fad4dd022b7d5b9d684"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.4.0.aar",
          "url": "idnow-android-eid-sdk-2.4.0.aar",
          "size": 5698631,
          "sha512": "623bb25333edae5745a56c13de0d93996a294c620fb25d405f1e00048771bd41ff50fb33f75a60463c6f02786b91f0c577e55deca9be144fde8cf7c4c13afa6a",
          "sha256": "973752cee3a17030e2ef7060998776766c1fdeeacd7e93749bf35bd2e9fe4d53",
          "sha1": "dd042c3b1e488997aca282730faf1138a330e7dc",
          "md5": "8afb1b036b906fad4dd022b7d5b9d684"
        }
      ]
    }
  ]
}
