{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.1.0.aar",
          "url": "idnow-android-eid-sdk-3.1.0.aar",
          "size": 5606944,
          "sha512": "8f4efb0aaa100a9e4cf1392c0e2fdae645e22ec7469ea6840c19abed4e67a42df701267784f5b7ca0ddcb0d2fb846a040e6c055f565a091146f31294700539b7",
          "sha256": "c7385da71136d8d50f902f6c828b85c837c17bd4bd15b5ea729faa6eb3b7bd8e",
          "sha1": "191d0459e50813f0408bceaa4200d28a4a9a6512",
          "md5": "caf95c7645a438853da898cc218e4a41"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.1.0.aar",
          "url": "idnow-android-eid-sdk-3.1.0.aar",
          "size": 5606944,
          "sha512": "8f4efb0aaa100a9e4cf1392c0e2fdae645e22ec7469ea6840c19abed4e67a42df701267784f5b7ca0ddcb0d2fb846a040e6c055f565a091146f31294700539b7",
          "sha256": "c7385da71136d8d50f902f6c828b85c837c17bd4bd15b5ea729faa6eb3b7bd8e",
          "sha1": "191d0459e50813f0408bceaa4200d28a4a9a6512",
          "md5": "caf95c7645a438853da898cc218e4a41"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.1.0-sources.jar",
          "url": "idnow-android-eid-sdk-3.1.0-sources.jar",
          "size": 245733,
          "sha512": "92618d5a80faf05052300a39a761ddcc064f4db9615697f55f0728b4d91a65373d8885391fe41a8af350c2654e9f22ad5c95d47ed20596c0383f8fb143f8a8d8",
          "sha256": "d3f7832f012dcb94da76285a7030d167e2ce5fd164fca66e4c4cde210267086a",
          "sha1": "57eeef7f9473585a8e287d7d4b945fd2784f77d4",
          "md5": "efc0f90853f6b5a8d0a9dc0c5e54c85b"
        }
      ]
    }
  ]
}
