{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "3.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.5.5.aar",
          "url": "idnow-android-eid-sdk-3.5.5.aar",
          "size": 5855293,
          "sha512": "45aadfe948ee8cd050d1f0c16943231ad7b9c8a0e443af6bbce91ba424a00c350d1269f03138d69d0201cd359bd8c2a094e1fd1a023baa308ef3bc6f0a711194",
          "sha256": "0a1befb2d03f2a9a3432e100b908fb42908e71eefc28cd7f160d9a1eadb06a6e",
          "sha1": "f07460ba3b58873a84a6aa8e69506fab6dbf1150",
          "md5": "69a6a1d8c8e56abfeeb4fcdeb8c4873f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "9.0.26"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.5.5.aar",
          "url": "idnow-android-eid-sdk-3.5.5.aar",
          "size": 5855293,
          "sha512": "45aadfe948ee8cd050d1f0c16943231ad7b9c8a0e443af6bbce91ba424a00c350d1269f03138d69d0201cd359bd8c2a094e1fd1a023baa308ef3bc6f0a711194",
          "sha256": "0a1befb2d03f2a9a3432e100b908fb42908e71eefc28cd7f160d9a1eadb06a6e",
          "sha1": "f07460ba3b58873a84a6aa8e69506fab6dbf1150",
          "md5": "69a6a1d8c8e56abfeeb4fcdeb8c4873f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-3.5.5-sources.jar",
          "url": "idnow-android-eid-sdk-3.5.5-sources.jar",
          "size": 295827,
          "sha512": "89b2bca52ec93108240d53f001ee42319161592fc31fe6a9c1de505057d89f4f8c3d176f5d9c85352788fed70e8f50a81eb6685ae9dfe7277ed953b6b0bf4c98",
          "sha256": "af78f815b6fb7fedcd6076d19d8550a7737f39cf1ea85936b5d3571dc076f8fa",
          "sha1": "56a0b560f98b351b0fb2dd002b88a8cf9414724e",
          "md5": "a8bd1954c2008a1e8e0a0bb2cf5dc5e8"
        }
      ]
    }
  ]
}
