{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.3.aar",
          "url": "idnow-android-eid-sdk-2.7.3.aar",
          "size": 5699775,
          "sha512": "fb5cf8709d0f8124172cbb55a25ba3436325e71b7d762d99dbfbe5eac4a6c3049d57aff704968500e88db9f0ee05b92d3d95ad2106e8c6d84ca735740e5c1f0d",
          "sha256": "92c70e21e5114a5779ff989924942b95bd4a5e41a56bb778ece5b3fe21d0b914",
          "sha1": "4aad8de755f56ff1ea4da1619ab9341b0cc2d913",
          "md5": "228e2ad9e10e26666ce3753c5e548673"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "AndroidPdfViewerV1",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.3.aar",
          "url": "idnow-android-eid-sdk-2.7.3.aar",
          "size": 5699775,
          "sha512": "fb5cf8709d0f8124172cbb55a25ba3436325e71b7d762d99dbfbe5eac4a6c3049d57aff704968500e88db9f0ee05b92d3d95ad2106e8c6d84ca735740e5c1f0d",
          "sha256": "92c70e21e5114a5779ff989924942b95bd4a5e41a56bb778ece5b3fe21d0b914",
          "sha1": "4aad8de755f56ff1ea4da1619ab9341b0cc2d913",
          "md5": "228e2ad9e10e26666ce3753c5e548673"
        }
      ]
    }
  ]
}
