{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hxvvrkb4lrg57ciapdvfu32gja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.2.2.aar",
          "url": "idnow-android-eid-sdk-2.2.2.aar",
          "size": 5695150,
          "sha512": "068b943b24aa48f3d24ac9007755b1fb28374aaaad91f115c672abee1b360282e6fd4941e6e4e93a2a83e078c9adfb3146518e5a1d31e191ed0126d96eff8be7",
          "sha256": "c44b80ce49016873477723b902dd757896e1b822d859412718107c163570ad9b",
          "sha1": "9c18d547c88b77d99f0e3b02568832c41578719d",
          "md5": "f1af957cf2f2ff61598c12659a2e6dd5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.2.2.aar",
          "url": "idnow-android-eid-sdk-2.2.2.aar",
          "size": 5695150,
          "sha512": "068b943b24aa48f3d24ac9007755b1fb28374aaaad91f115c672abee1b360282e6fd4941e6e4e93a2a83e078c9adfb3146518e5a1d31e191ed0126d96eff8be7",
          "sha256": "c44b80ce49016873477723b902dd757896e1b822d859412718107c163570ad9b",
          "sha1": "9c18d547c88b77d99f0e3b02568832c41578719d",
          "md5": "f1af957cf2f2ff61598c12659a2e6dd5"
        }
      ]
    }
  ]
}
