{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rstajdl77rcdroliirhd5dnlae"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.0.0.aar",
          "url": "idnow-android-eid-sdk-2.0.0.aar",
          "size": 4199826,
          "sha512": "a34c4fc0d45a25efc5a5753517b214e8543de7b34ea04e84bc413ae863548a7862e3c4987ee9087e54c7cd30def7978eeaf67d4423539e912391df2dd8979253",
          "sha256": "52dfde1d2a3c028108bae51e305b5e2547b685a7e31bc1f57e1276ecc659256a",
          "sha1": "4ae295300ce26a1c53a96247ae1a6b6af3159dbd",
          "md5": "d74b215b24d12bc3fe6f9dc34a74e93e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.0.0.aar",
          "url": "idnow-android-eid-sdk-2.0.0.aar",
          "size": 4199826,
          "sha512": "a34c4fc0d45a25efc5a5753517b214e8543de7b34ea04e84bc413ae863548a7862e3c4987ee9087e54c7cd30def7978eeaf67d4423539e912391df2dd8979253",
          "sha256": "52dfde1d2a3c028108bae51e305b5e2547b685a7e31bc1f57e1276ecc659256a",
          "sha1": "4ae295300ce26a1c53a96247ae1a6b6af3159dbd",
          "md5": "d74b215b24d12bc3fe6f9dc34a74e93e"
        }
      ]
    }
  ]
}
