{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "irkmm7z5lfgdfd6hvsxwuvakte"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-1.8.0.aar",
          "url": "idnow-android-eid-sdk-1.8.0.aar",
          "size": 3912439,
          "sha512": "d3b93a4fc90b2835a1750c3b7296b08e4fc967a89ec64d68cfd05b1289ce8870922344b5a032f06bd62967150f5550c5663ccebf3744cc3a66930c7b021984e7",
          "sha256": "cc4b834407cd482bb5db4bc21078e798003b6e2fa825d81676234c66e3372398",
          "sha1": "0e959bc6a96e51f0e97f628806d9f3c17ff8581d",
          "md5": "7b010c6f6f4f8dc6ffafad06b68a1f7d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-1.8.0.aar",
          "url": "idnow-android-eid-sdk-1.8.0.aar",
          "size": 3912439,
          "sha512": "d3b93a4fc90b2835a1750c3b7296b08e4fc967a89ec64d68cfd05b1289ce8870922344b5a032f06bd62967150f5550c5663ccebf3744cc3a66930c7b021984e7",
          "sha256": "cc4b834407cd482bb5db4bc21078e798003b6e2fa825d81676234c66e3372398",
          "sha1": "0e959bc6a96e51f0e97f628806d9f3c17ff8581d",
          "md5": "7b010c6f6f4f8dc6ffafad06b68a1f7d"
        }
      ]
    }
  ]
}
