{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.10.0.aar",
          "url": "idnow-android-eid-sdk-2.10.0.aar",
          "size": 5697077,
          "sha512": "9159075406f56c1a6e2c8cae602d01b338137791cd381e45c7a032e34ba818e59f0547579f5f01b62a2106f353ff6737a194f1a77e1b7c5de1c31a54a9d5c080",
          "sha256": "423d3a0fa81a5465149f183b8b52438ba3fc0e28a596a1090241ae63e33ac2bc",
          "sha1": "c4ac3283e5c735e549bb63845bc2c02348a2a4d5",
          "md5": "943a11c5abff3cf790e2dbb788eed1c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.10.0.aar",
          "url": "idnow-android-eid-sdk-2.10.0.aar",
          "size": 5697077,
          "sha512": "9159075406f56c1a6e2c8cae602d01b338137791cd381e45c7a032e34ba818e59f0547579f5f01b62a2106f353ff6737a194f1a77e1b7c5de1c31a54a9d5c080",
          "sha256": "423d3a0fa81a5465149f183b8b52438ba3fc0e28a596a1090241ae63e33ac2bc",
          "sha1": "c4ac3283e5c735e549bb63845bc2c02348a2a4d5",
          "md5": "943a11c5abff3cf790e2dbb788eed1c6"
        }
      ]
    }
  ]
}
