{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "samizmhtqfavlkcx5cvwbkkjey"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.3.aar",
          "url": "idnow-android-eid-sdk-2.5.3.aar",
          "size": 5699641,
          "sha512": "ae911affd2def2d72755ad50a61231d6d7d1fb6c01fd536adeecfbecdc00e542c34ec84d2575b1fd7a098630f313bef903f4ada16c89b299ed44d569af9bca9b",
          "sha256": "d5ad07f855e5bd60f7be3548c6faf110f648dbc227ab1ad2aafaadcd0b252638",
          "sha1": "d56487df63538a9359be61532abefb9d8b775c31",
          "md5": "166f77247081587240444bfe10469a74"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.3.aar",
          "url": "idnow-android-eid-sdk-2.5.3.aar",
          "size": 5699641,
          "sha512": "ae911affd2def2d72755ad50a61231d6d7d1fb6c01fd536adeecfbecdc00e542c34ec84d2575b1fd7a098630f313bef903f4ada16c89b299ed44d569af9bca9b",
          "sha256": "d5ad07f855e5bd60f7be3548c6faf110f648dbc227ab1ad2aafaadcd0b252638",
          "sha1": "d56487df63538a9359be61532abefb9d8b775c31",
          "md5": "166f77247081587240444bfe10469a74"
        }
      ]
    }
  ]
}
