{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "s2dxodrrzbg6nkwphzv7f3uiry"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-1.5.0.aar",
          "url": "idnow-android-eid-sdk-1.5.0.aar",
          "size": 5252560,
          "sha512": "2b6bccad4c7e0d11686329c729c1705d97ef3b85251cf9485b84af75155cee26e97df3d17c36a8d24c7197c8fc52ccbc7abe683622210a35572ca765fd06f429",
          "sha256": "8b3f72191a1a97b57cfdd9eefa6270539759766eba8988f3cf16d3d510014760",
          "sha1": "9e39de410314354b348a5b1ea0728adfefff9c6a",
          "md5": "af353ac24f4a2935ce6a40ecc8d1a34b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-1.5.0.aar",
          "url": "idnow-android-eid-sdk-1.5.0.aar",
          "size": 5252560,
          "sha512": "2b6bccad4c7e0d11686329c729c1705d97ef3b85251cf9485b84af75155cee26e97df3d17c36a8d24c7197c8fc52ccbc7abe683622210a35572ca765fd06f429",
          "sha256": "8b3f72191a1a97b57cfdd9eefa6270539759766eba8988f3cf16d3d510014760",
          "sha1": "9e39de410314354b348a5b1ea0728adfefff9c6a",
          "md5": "af353ac24f4a2935ce6a40ecc8d1a34b"
        }
      ]
    }
  ]
}
