{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.5.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7vdnmlvgtjaihicpnayxi2h5qi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.1.1.aar",
          "url": "idnow-android-eid-sdk-2.5.1.1.aar",
          "size": 5711620,
          "sha512": "9a531c42d1a30448536f4d95964c5925713386104e948cdc49c0b6947676e2efd83435bcfdf91a91ade73b3aef821183e2cb6258c26be43aa879b9bb2f2580c3",
          "sha256": "0d6f317f02361aae20901d8ea3c10be502dc399fcda81671fd1eae742cd36e29",
          "sha1": "fa901e7d3b3ca1c6836ce176fcd236799e7fe912",
          "md5": "15e50c11fdaca5ce21961b2e2d4f4bb4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.1.1.aar",
          "url": "idnow-android-eid-sdk-2.5.1.1.aar",
          "size": 5711620,
          "sha512": "9a531c42d1a30448536f4d95964c5925713386104e948cdc49c0b6947676e2efd83435bcfdf91a91ade73b3aef821183e2cb6258c26be43aa879b9bb2f2580c3",
          "sha256": "0d6f317f02361aae20901d8ea3c10be502dc399fcda81671fd1eae742cd36e29",
          "sha1": "fa901e7d3b3ca1c6836ce176fcd236799e7fe912",
          "md5": "15e50c11fdaca5ce21961b2e2d4f4bb4"
        }
      ]
    }
  ]
}
