{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "dgj4b7uxyrerzhyyozsnyz3vqq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.1.0.aar",
          "url": "idnow-android-eid-sdk-2.1.0.aar",
          "size": 5688475,
          "sha512": "a0128db60e16e74a2c8310bc5f742852e0d2c4bbde0326791af65ea600eeb540e293a42019edb7aee08a46ce3ed9aca02c7abf5e769cc50adfbcef34ec143df0",
          "sha256": "02b33840b84afaf651d03046f8a188f84c41fb52b1e88b0ec07e14a7804d6733",
          "sha1": "e7ea5f6be02cfb882e81841cdf395326df9f88c4",
          "md5": "5b3709db64eb1267c9be0cc6c0914b9b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.1.0.aar",
          "url": "idnow-android-eid-sdk-2.1.0.aar",
          "size": 5688475,
          "sha512": "a0128db60e16e74a2c8310bc5f742852e0d2c4bbde0326791af65ea600eeb540e293a42019edb7aee08a46ce3ed9aca02c7abf5e769cc50adfbcef34ec143df0",
          "sha256": "02b33840b84afaf651d03046f8a188f84c41fb52b1e88b0ec07e14a7804d6733",
          "sha1": "e7ea5f6be02cfb882e81841cdf395326df9f88c4",
          "md5": "5b3709db64eb1267c9be0cc6c0914b9b"
        }
      ]
    }
  ]
}
