{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.8.1.aar",
          "url": "idnow-android-eid-sdk-2.8.1.aar",
          "size": 5694307,
          "sha512": "390eb60fb044ada8322ae29a8671039c8dd144652484363f02a5d1e015d8c8a5721d5af0ca46a88377f23610483bada569bd14c0162c54b3f48ec582714fcb9b",
          "sha256": "206ef786051885dfbb9de124cef6fddeede8278ec52abb74ecc3ad1cf4a5be12",
          "sha1": "5b24b95878e66effa2e734d90ef17643ddea87bf",
          "md5": "0483b2bb362fcb17b4330474046c3129"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.8.1.aar",
          "url": "idnow-android-eid-sdk-2.8.1.aar",
          "size": 5694307,
          "sha512": "390eb60fb044ada8322ae29a8671039c8dd144652484363f02a5d1e015d8c8a5721d5af0ca46a88377f23610483bada569bd14c0162c54b3f48ec582714fcb9b",
          "sha256": "206ef786051885dfbb9de124cef6fddeede8278ec52abb74ecc3ad1cf4a5be12",
          "sha1": "5b24b95878e66effa2e734d90ef17643ddea87bf",
          "md5": "0483b2bb362fcb17b4330474046c3129"
        }
      ]
    }
  ]
}
