{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "dh4s4je62vfhxfuncrcv3dhbci"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.0.1.aar",
          "url": "idnow-android-eid-sdk-2.0.1.aar",
          "size": 4206621,
          "sha512": "73bd963e2b88250a980251677bc13c5f9f1837056d4b04a3557d488c7fd47e8b3f33f0e455a41b9712b258b39cf0d962cac6e7ba6ea5fd24d21b8e96d2a78ced",
          "sha256": "cb24583c895e80ae0b153ea392683c0391395cefe9c0480169fe6f993450e035",
          "sha1": "84581523d03df4c8654e7b7d14a27890b572760d",
          "md5": "1969f35f595722a647e764c7cb322bde"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.0.1.aar",
          "url": "idnow-android-eid-sdk-2.0.1.aar",
          "size": 4206621,
          "sha512": "73bd963e2b88250a980251677bc13c5f9f1837056d4b04a3557d488c7fd47e8b3f33f0e455a41b9712b258b39cf0d962cac6e7ba6ea5fd24d21b8e96d2a78ced",
          "sha256": "cb24583c895e80ae0b153ea392683c0391395cefe9c0480169fe6f993450e035",
          "sha1": "84581523d03df4c8654e7b7d14a27890b572760d",
          "md5": "1969f35f595722a647e764c7cb322bde"
        }
      ]
    }
  ]
}
