{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.4.aar",
          "url": "idnow-android-eid-sdk-2.7.4.aar",
          "size": 5699805,
          "sha512": "da988724cfd2a927cad2e6513a240a446a6dca92e829c2d787a833b600ac3e0fb83668e05f83dee214a0a9cd24cdc2d83f6df944f34ad4e6fe812056b909ab25",
          "sha256": "0579b2b0e71c98e9db4fd987aa40a2d52683d26bbd79c54668335d59daa7f8db",
          "sha1": "34246f34129ba210dd4c4ec4408e08a4ddc1e386",
          "md5": "c1055cd2449269bc7865aa7fe829d9f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.TalbotGooday",
          "module": "AndroidPdfViewer",
          "version": {
            "requires": "3.1.0-beta.3"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.4.aar",
          "url": "idnow-android-eid-sdk-2.7.4.aar",
          "size": 5699805,
          "sha512": "da988724cfd2a927cad2e6513a240a446a6dca92e829c2d787a833b600ac3e0fb83668e05f83dee214a0a9cd24cdc2d83f6df944f34ad4e6fe812056b909ab25",
          "sha256": "0579b2b0e71c98e9db4fd987aa40a2d52683d26bbd79c54668335d59daa7f8db",
          "sha1": "34246f34129ba210dd4c4ec4408e08a4ddc1e386",
          "md5": "c1055cd2449269bc7865aa7fe829d9f8"
        }
      ]
    }
  ]
}
