{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "egbaewrwxzaafjofp7zxdgpyie"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.4.aar",
          "url": "idnow-android-eid-sdk-2.5.4.aar",
          "size": 5699651,
          "sha512": "5f9e59637883ba892a138619219e45495007c85d09cdd71234acbd4c93ce035feb15d90d3ba3316c46bf0bc1290ea023f0af1e38fe9b7df437afe75ae0adc6c5",
          "sha256": "99bf4eede74b2b85eee9679dafce45391af09b201d1a395b45c8fd37bf1bbf2d",
          "sha1": "4dce6274c39ed2b44ea20b8584bba91d8ef3cd21",
          "md5": "682e3e833b55f04d435391f8274cb3e7"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.4.aar",
          "url": "idnow-android-eid-sdk-2.5.4.aar",
          "size": 5699651,
          "sha512": "5f9e59637883ba892a138619219e45495007c85d09cdd71234acbd4c93ce035feb15d90d3ba3316c46bf0bc1290ea023f0af1e38fe9b7df437afe75ae0adc6c5",
          "sha256": "99bf4eede74b2b85eee9679dafce45391af09b201d1a395b45c8fd37bf1bbf2d",
          "sha1": "4dce6274c39ed2b44ea20b8584bba91d8ef3cd21",
          "md5": "682e3e833b55f04d435391f8274cb3e7"
        }
      ]
    }
  ]
}
