{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ifutyqfkm5clvbcvvohvpehrga"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.1.aar",
          "url": "idnow-android-eid-sdk-2.7.1.aar",
          "size": 5707530,
          "sha512": "508df73d610e5f982785d01b2b162a5ce7f288c4d3068c16d4d7c1cc00d43fcf16115de64946ce5bbe92b9bb7d25feb3046b51c0aafa7cd38790d7de9d03f63c",
          "sha256": "b3fc304f3614c75a6bc7a5cc90cffa1cb20cda4922db8a87670afd06337c4a96",
          "sha1": "cca286af2480341b44e5fbc4159e900c0bfc25e0",
          "md5": "1104a65bdf8dfbb46fd5bec4377008ad"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.1.aar",
          "url": "idnow-android-eid-sdk-2.7.1.aar",
          "size": 5707530,
          "sha512": "508df73d610e5f982785d01b2b162a5ce7f288c4d3068c16d4d7c1cc00d43fcf16115de64946ce5bbe92b9bb7d25feb3046b51c0aafa7cd38790d7de9d03f63c",
          "sha256": "b3fc304f3614c75a6bc7a5cc90cffa1cb20cda4922db8a87670afd06337c4a96",
          "sha1": "cca286af2480341b44e5fbc4159e900c0bfc25e0",
          "md5": "1104a65bdf8dfbb46fd5bec4377008ad"
        }
      ]
    }
  ]
}
