{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.7.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "sqmile5dcra2hgttqcftsaogze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.0-beta1.aar",
          "url": "idnow-android-eid-sdk-2.7.0-beta1.aar",
          "size": 5708202,
          "sha512": "2053a7683a21ad1b2408ad6ddd997ae16adc1096e357737b0abafba501b3e1a08b0326145913cfd47213adf254ec90be41fa7c3c4e534da19fbef45ca63fa660",
          "sha256": "d5d5e13ef4f94c31239babd6fadaada2d2842f2bda6534d2f8e02dbe21eabd27",
          "sha1": "66fdbe5a3bc24e0c2c7e6bc92b57fdb0e06597be",
          "md5": "d95d6a07bce612c64b59c757e5b63af9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.7.0-beta1.aar",
          "url": "idnow-android-eid-sdk-2.7.0-beta1.aar",
          "size": 5708202,
          "sha512": "2053a7683a21ad1b2408ad6ddd997ae16adc1096e357737b0abafba501b3e1a08b0326145913cfd47213adf254ec90be41fa7c3c4e534da19fbef45ca63fa660",
          "sha256": "d5d5e13ef4f94c31239babd6fadaada2d2842f2bda6534d2f8e02dbe21eabd27",
          "sha1": "66fdbe5a3bc24e0c2c7e6bc92b57fdb0e06597be",
          "md5": "d95d6a07bce612c64b59c757e5b63af9"
        }
      ]
    }
  ]
}
