{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.sdk",
    "module": "idnow-android-sdk",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "uos6tedbejb7reik4dpz3z2u4u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": null,
          "module": "insights-1.2",
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "insights-1.2",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-5.0.0.aar",
          "url": "idnow-android-sdk-5.0.0.aar",
          "size": 35720771,
          "sha512": "baf8414d90c6a1cf6a6c4df9d878cd6bd072f876a02145d0bcb7e4843be17ef5a18411aadd356c08a7b59e19d112808367be92f427cae19736d5537cddcbd5ce",
          "sha256": "d496ab82f16b8649810c07a482ab60da844186516c83038b1e0d50cc002a2f04",
          "sha1": "a63e2b9f6687d9241ebea3e444428f0dc0ab0fe9",
          "md5": "8a9debc632b15b59d6754fc044980aa4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": null,
          "module": "insights-1.2",
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "insights-1.2",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-5.0.0.aar",
          "url": "idnow-android-sdk-5.0.0.aar",
          "size": 35720771,
          "sha512": "baf8414d90c6a1cf6a6c4df9d878cd6bd072f876a02145d0bcb7e4843be17ef5a18411aadd356c08a7b59e19d112808367be92f427cae19736d5537cddcbd5ce",
          "sha256": "d496ab82f16b8649810c07a482ab60da844186516c83038b1e0d50cc002a2f04",
          "sha1": "a63e2b9f6687d9241ebea3e444428f0dc0ab0fe9",
          "md5": "8a9debc632b15b59d6754fc044980aa4"
        }
      ]
    }
  ]
}
