{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.sdk",
    "module": "idnow-android-sdk",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "chtn4yum7fgizkvit7vt5onvua"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-5.0.0.aar",
          "url": "idnow-android-sdk-5.0.0.aar",
          "size": 35847433,
          "sha512": "a4fe89e75ec5f6443874e238ae5d4a41b2bfc804bd845a14af5a675dc02bc0795246250650647ec85411fbebc7e17f3e96c50bc09a5f775c15c323f8191dfb3d",
          "sha256": "cd78a536874ae89fbb5ec291dbcc5fc8583a085e21f07f9533ca17b639e23d9c",
          "sha1": "62d030ac6fda358fbaaffbca7b3bd2086799e0c8",
          "md5": "6323d6a70ef37465b390acb7a729dfaf"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-5.0.0.aar",
          "url": "idnow-android-sdk-5.0.0.aar",
          "size": 35847433,
          "sha512": "a4fe89e75ec5f6443874e238ae5d4a41b2bfc804bd845a14af5a675dc02bc0795246250650647ec85411fbebc7e17f3e96c50bc09a5f775c15c323f8191dfb3d",
          "sha256": "cd78a536874ae89fbb5ec291dbcc5fc8583a085e21f07f9533ca17b639e23d9c",
          "sha1": "62d030ac6fda358fbaaffbca7b3bd2086799e0c8",
          "md5": "6323d6a70ef37465b390acb7a729dfaf"
        }
      ]
    }
  ]
}
