{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "2c6jpa7qifft5ljqwq3fmingn4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.0.3.aar",
          "url": "idnow-android-eid-sdk-2.0.3.aar",
          "size": 8745517,
          "sha512": "d72350fe853fbd3ce1cadf38a3535339faa4ae048a456d9adec96762a9cd9216aec3134578153a46ea1816dd3b87fc98bbfbfba226429e21ea6d9b3537dd63c4",
          "sha256": "be820c0e9aa07494179265e5848e68375609e155352e0f0079571fa93845e4ad",
          "sha1": "cc3f280eb93c0ce8cc7852171a5e4e25c0c3ad88",
          "md5": "c7abc7707361484c0965c2be1878b712"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.0.3.aar",
          "url": "idnow-android-eid-sdk-2.0.3.aar",
          "size": 8745517,
          "sha512": "d72350fe853fbd3ce1cadf38a3535339faa4ae048a456d9adec96762a9cd9216aec3134578153a46ea1816dd3b87fc98bbfbfba226429e21ea6d9b3537dd63c4",
          "sha256": "be820c0e9aa07494179265e5848e68375609e155352e0f0079571fa93845e4ad",
          "sha1": "cc3f280eb93c0ce8cc7852171a5e4e25c0c3ad88",
          "md5": "c7abc7707361484c0965c2be1878b712"
        }
      ]
    }
  ]
}
