{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fz4mrawwm5bdtbwubni6sy46em"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.2.aar",
          "url": "idnow-android-eid-sdk-2.5.2.aar",
          "size": 5699645,
          "sha512": "465edfa15e5473b283bfb72f5f50724abcacb3e7ed862447ce10f87c7d3a9a0cfe58306b32146e40fa564ab493db642333f2821942fdd4e8078adb099a8eae79",
          "sha256": "2b0a3ea2a5864c7bb9e4e41c77250d567596653f1bc506acf2f621f0fa74cdb8",
          "sha1": "685593db7e966277062ebc13be31d2eb545c894f",
          "md5": "2e063f075d0c6db9f2da117c5c864087"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.2.aar",
          "url": "idnow-android-eid-sdk-2.5.2.aar",
          "size": 5699645,
          "sha512": "465edfa15e5473b283bfb72f5f50724abcacb3e7ed862447ce10f87c7d3a9a0cfe58306b32146e40fa564ab493db642333f2821942fdd4e8078adb099a8eae79",
          "sha256": "2b0a3ea2a5864c7bb9e4e41c77250d567596653f1bc506acf2f621f0fa74cdb8",
          "sha1": "685593db7e966277062ebc13be31d2eb545c894f",
          "md5": "2e063f075d0c6db9f2da117c5c864087"
        }
      ]
    }
  ]
}
