{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "b7bxpvyb2bchjhwexbepenwk4y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.2.1.aar",
          "url": "idnow-android-eid-sdk-2.2.1.aar",
          "size": 5688665,
          "sha512": "35d5f28a882a11c5e0a0479f20399117b172c63c7b00c4a023c5c675c586d098a8645fbc48a79893f5246ebd482e852858ee1185a3dee0ef6a00356d1ffe3ec5",
          "sha256": "cc429f240bd0e64eee192fbbf5cd569ba5002bb213a9d078749776626d5a4459",
          "sha1": "2d567e6b5fe7fdcaeb1d3d430c6ab11fd39dd2ff",
          "md5": "c1a51781fade2a49e4e61107561e2711"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.2.1.aar",
          "url": "idnow-android-eid-sdk-2.2.1.aar",
          "size": 5688665,
          "sha512": "35d5f28a882a11c5e0a0479f20399117b172c63c7b00c4a023c5c675c586d098a8645fbc48a79893f5246ebd482e852858ee1185a3dee0ef6a00356d1ffe3ec5",
          "sha256": "cc429f240bd0e64eee192fbbf5cd569ba5002bb213a9d078749776626d5a4459",
          "sha1": "2d567e6b5fe7fdcaeb1d3d430c6ab11fd39dd2ff",
          "md5": "c1a51781fade2a49e4e61107561e2711"
        }
      ]
    }
  ]
}
