{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "aetuxumpszcjnf42zqozezk3du"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.1.aar",
          "url": "idnow-android-eid-sdk-2.5.1.aar",
          "size": 5698904,
          "sha512": "7d7c1077ab012c0328cbd9c1b9bf99cccff276b45eb492110e9b84c83ebaf79dbdb48ecee7e2635653e50759b86f1ec038f10bfbc0b1b357f7df493231dc0b33",
          "sha256": "474d819e7cad2d1f209a0f8ee530f06d387c727cd80457661f1d5078eebb1918",
          "sha1": "69b68dbbda11fbfa1ec6182975dfe3547d602881",
          "md5": "83674b5bee85ccd8f375624546a2d3b4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.5.1.aar",
          "url": "idnow-android-eid-sdk-2.5.1.aar",
          "size": 5698904,
          "sha512": "7d7c1077ab012c0328cbd9c1b9bf99cccff276b45eb492110e9b84c83ebaf79dbdb48ecee7e2635653e50759b86f1ec038f10bfbc0b1b357f7df493231dc0b33",
          "sha256": "474d819e7cad2d1f209a0f8ee530f06d387c727cd80457661f1d5078eebb1918",
          "sha1": "69b68dbbda11fbfa1ec6182975dfe3547d602881",
          "md5": "83674b5bee85ccd8f375624546a2d3b4"
        }
      ]
    }
  ]
}
