{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.sdk",
    "module": "idnow-android-sdk",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "itmpqgtkjvaubiitmipx5wgn7a"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-6.1.3.aar",
          "url": "idnow-android-sdk-6.1.3.aar",
          "size": 16416991,
          "sha512": "74dbbc733355a66294ac8670d45669396d37f1de166ffac45ffde7c6be3eb2aa181f5173516f85d55876ed91a71c2a08e44d0bd1d4ca80e393c1c609a6b57e4b",
          "sha256": "9788d3cf3fe4edc29aef506ae797fefd772d335cbc4d5182ddbe805c74ce6608",
          "sha1": "9d98fe2181162272c74c6b50f97b24d92dbacc52",
          "md5": "2fdbfb37226bc0c07a7f32635b0ebf99"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-6.1.3.aar",
          "url": "idnow-android-sdk-6.1.3.aar",
          "size": 16416991,
          "sha512": "74dbbc733355a66294ac8670d45669396d37f1de166ffac45ffde7c6be3eb2aa181f5173516f85d55876ed91a71c2a08e44d0bd1d4ca80e393c1c609a6b57e4b",
          "sha256": "9788d3cf3fe4edc29aef506ae797fefd772d335cbc4d5182ddbe805c74ce6608",
          "sha1": "9d98fe2181162272c74c6b50f97b24d92dbacc52",
          "md5": "2fdbfb37226bc0c07a7f32635b0ebf99"
        }
      ]
    }
  ]
}
