{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ebfs7edxfvcjxnsglxi4g3onhe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.6.0.aar",
          "url": "idnow-android-eid-sdk-2.6.0.aar",
          "size": 5693266,
          "sha512": "9897bd3f9beb5c93d6017b1536c77054d60cfef2f7d98e7c0d7e7174c66fd30307a890ad670773ac5a3285e9bf1834b3b4b05d7774897975c6801bb628667d41",
          "sha256": "37b2747e0a091f84d81c5401016bb6aaefe77a3a1e4ee7e117a9afc217ee074b",
          "sha1": "fc648552c00b0d9943293e1b2d91eb93d20242ba",
          "md5": "dc40195c61b6e76c2de33b457b35de24"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-2.6.0.aar",
          "url": "idnow-android-eid-sdk-2.6.0.aar",
          "size": 5693266,
          "sha512": "9897bd3f9beb5c93d6017b1536c77054d60cfef2f7d98e7c0d7e7174c66fd30307a890ad670773ac5a3285e9bf1834b3b4b05d7774897975c6801bb628667d41",
          "sha256": "37b2747e0a091f84d81c5401016bb6aaefe77a3a1e4ee7e117a9afc217ee074b",
          "sha1": "fc648552c00b0d9943293e1b2d91eb93d20242ba",
          "md5": "dc40195c61b6e76c2de33b457b35de24"
        }
      ]
    }
  ]
}
