{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.sdk",
    "module": "idnow-android-sdk",
    "version": "9.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-9.2.1.aar",
          "url": "idnow-android-sdk-9.2.1.aar",
          "size": 11499077,
          "sha512": "0c598acb1e030ae5b765d711ee733bd743dc748304752bcace25f63afc948a36b881c3f07d8131f7e664333621d6375ca03933802cb6cbae450e8db8b85f9006",
          "sha256": "217f4ca316362fea94be400ce4948c87229d174d0dc0040b3f0667159df13c35",
          "sha1": "e16ceda8dbea63a5e16c6113334ee4221109e25f",
          "md5": "eba8f82e223000b6ddab2a96e262914b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.10.9"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-sdk-9.2.1.aar",
          "url": "idnow-android-sdk-9.2.1.aar",
          "size": 11499077,
          "sha512": "0c598acb1e030ae5b765d711ee733bd743dc748304752bcace25f63afc948a36b881c3f07d8131f7e664333621d6375ca03933802cb6cbae450e8db8b85f9006",
          "sha256": "217f4ca316362fea94be400ce4948c87229d174d0dc0040b3f0667159df13c35",
          "sha1": "e16ceda8dbea63a5e16c6113334ee4221109e25f",
          "md5": "eba8f82e223000b6ddab2a96e262914b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "idnow-android-sdk-9.2.1-sources.jar",
          "url": "idnow-android-sdk-9.2.1-sources.jar",
          "size": 714901,
          "sha512": "97b9607693b4f0f0a076c918cb7f3121d7789155d95fe72e4c031a93599958c0811922e9c0493c8656ee6c50430b53ef27c5073a97e4c8a8590da7a4a5d73ea0",
          "sha256": "ac8a05bb6dd7d15a17a6a2a7c6b4027a775b7b22238e522714c4e7dc0ac163fe",
          "sha1": "aca35f1a11822aae76f7aef8677532dce13f0310",
          "md5": "31aa5d6f416f54fb34029bd5f4e857d5"
        }
      ]
    }
  ]
}
