{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.eid",
    "module": "idnow-android-eid-sdk",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3iurtqoqvffofj4dkq5ffqiub4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-android-eid-sdk-1.7.0.aar",
          "url": "idnow-android-eid-sdk-1.7.0.aar",
          "size": 5265904,
          "sha512": "ff98fbfbbf3635cf958fb2d301b484643cbebc7ef91724d7cc1e3b50d6f69dce83fef78da510e24c45cdb1823adc1c30f737df5284fceef2b1f051962f2eec2b",
          "sha256": "d3ef60a6a3fbd90ea0429b9dd5850bf5e414d6719f871f13a2e310738346e87c",
          "sha1": "b007cd6a22e745df1cb7449fb8120d5a6d993bd3",
          "md5": "309901be3d6771f49a0b3fd750451f30"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "idnow-android-eid-sdk-1.7.0.aar",
          "url": "idnow-android-eid-sdk-1.7.0.aar",
          "size": 5265904,
          "sha512": "ff98fbfbbf3635cf958fb2d301b484643cbebc7ef91724d7cc1e3b50d6f69dce83fef78da510e24c45cdb1823adc1c30f737df5284fceef2b1f051962f2eec2b",
          "sha256": "d3ef60a6a3fbd90ea0429b9dd5850bf5e414d6719f871f13a2e310738346e87c",
          "sha1": "b007cd6a22e745df1cb7449fb8120d5a6d993bd3",
          "md5": "309901be3d6771f49a0b3fd750451f30"
        }
      ]
    }
  ]
}
